Repository RubyMetric/chsrc, pull requests merged in 2024-12, with the labels that each got.

#129 Fix ROS Error
  src/recipe/os/APT/ROS.c
Labels: Bug, 操作系统, Linux

#150 Fix `Debian`, `Rocky` version detection
  src/recipe/os/APT/common.h
  src/recipe/os/YUM/Rocky-Linux.c
Labels: FixBug

#155 [UPDATE] Add new section to PR template
  .github/pull_request_template.md
Labels: 维护与贡献

#161 Feature winget release
  .github/workflows/winget.yml
  pkg/README.md
  src/chsrc-main.c
Labels: Release
