Repository RubyMetric/chsrc, pull requests merged in 2025-08, with the labels that each got.

#240 add speed test
  src/recipe/lang/Rust/rustup.c
Labels: 源

#271 尝试修复which不存在的问题
  src/framework/core.c
Labels: Linux

#276 为 Arch Linux (及 CN) 添加上海交通大学的镜像源
  src/chsrc-main.c
  src/recipe/os/pacman/Arch-Linux.c
Labels: os_target, 源
